import Link from "next/link";

export const metadata = {
  title: "Privacy Policy — The Long View",
  description:
    "What The Long View collects, why, and how to remove it.",
};

export default function PrivacyPage() {
  return (
    <div className="flex flex-col flex-1">
      <header className="border-b border-border">
        <div className="max-w-4xl mx-auto px-6 py-4 flex items-center gap-4">
          <Link
            href="/"
            className="text-sm text-muted hover:text-accent transition-colors"
          >
            ← All Headlines
          </Link>
          <div className="h-4 w-px bg-border" />
          <span
            className="text-sm font-medium"
            style={{ fontFamily: "var(--font-serif)" }}
          >
            The Long View
          </span>
        </div>
      </header>

      <main className="flex-1 max-w-4xl mx-auto px-6 py-12 w-full">
        <p className="text-xs uppercase tracking-widest text-muted mb-3">
          Last updated 29 April 2026
        </p>
        <h1
          className="text-4xl sm:text-5xl font-bold tracking-tight mb-6"
          style={{ fontFamily: "var(--font-serif)" }}
        >
          Privacy Policy
        </h1>

        <p className="text-lg text-muted leading-relaxed mb-10">
          The Long View pairs today&apos;s headlines with their historical
          context. To do that we keep accounts and store the histories we
          generate. This page explains what we collect and why.
        </p>

        <Section title="What we collect">
          <p>
            When you sign in with Google we receive your name, email address,
            and profile picture. When you request a history we store the
            headline, the generated analysis, and an identifier linking the
            request to your account.
          </p>
          <p>
            We use Vercel Analytics to count anonymous page views. No personal
            identifiers are sent.
          </p>
        </Section>

        <Section title="Why we collect it">
          <p>
            Accounts let us cache each generated history once and serve it to
            everyone afterwards — so your request also benefits the next
            reader. The user identifier on a history exists so we can remove
            content if asked, and to prevent abuse.
          </p>
        </Section>

        <Section title="Who else sees it">
          <p>
            Sign-in is handled by Firebase Authentication (Google Cloud). The
            app runs on Vercel. Histories are generated by Anthropic&apos;s
            Claude API. Each provider sees only what they need to do their
            job, governed by their own privacy policies.
          </p>
        </Section>

        <Section title="Your rights">
          <p>
            You can sign out at any time. You can ask us to delete your
            account and any histories attributed to you by emailing the
            address below; we&apos;ll do it within 30 days.
          </p>
        </Section>

        <Section title="Contact">
          <p>
            Questions or requests:{" "}
            <a
              href="mailto:hello@thelongview.org"
              className="text-accent hover:underline"
            >
              hello@thelongview.org
            </a>
          </p>
        </Section>
      </main>

      <footer className="border-t border-border mt-auto">
        <div className="max-w-4xl mx-auto px-6 py-6 text-center text-xs text-muted">
          <Link href="/" className="hover:text-accent transition-colors">
            ← Back to The Long View
          </Link>
        </div>
      </footer>
    </div>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="mb-10">
      <h2
        className="text-xs font-medium uppercase tracking-widest text-muted mb-3"
      >
        {title}
      </h2>
      <div className="space-y-4 text-base leading-relaxed">{children}</div>
    </section>
  );
}
